// Employee Interface
import * as Enums from "@/utils/enums";

export interface EmployeeDto {
    GUID: string;
    EmployeeID: string; // PK
    Username: string;
    Email: string;
    StocktakeSchedules?: StocktakeScheduleDto[]; // One-to-many relationship

    DisplayColor: string;
    FullName: string;
    EmailAddress: string;
}

// Stocktake Interface
export interface StocktakeDto {
    // GUID: string;
    ID: string; // PK
    Name: string;
    Description: string;
    Status: (typeof Enums.StocktakeStatus)[keyof typeof Enums.StocktakeStatus]; //'Draft' | 'Pending' | 'InProgress' | 'Completed';
    CreatedBy: string;
    CreatedDate: string;
    StartedDate: string | null;
    ScheduledDate: Date | string | null;
    CompletedDate: string | null;
    Notes: string;
    WarehouseID: string; // FK to Warehouse
    AssignedEmployeeID: string; // FK to Employee
    ModifiedDate: Date | null;
    ModifiedBy: string;
    RowVersion: string;
    WarehouseName: string;
    AssignedEmployeeFullName: string;
    StocktakeTemplateID: null | string;
    StocktakeTemplateName: null | string;
    StocktakeType: number;
    ValidityPeriodHours: number;
    AssignedManagerEmployeeID: string;
    AssignedManagerEmployeeFullName: string;

    // Relationships
    // Warehouse?: WarehouseDto; // Many-to-one relationship
    // StocktakeItems?: StocktakeItemDto[]; // One-to-many relationship
    // StocktakeFilters?: StocktakeFilterDto[]; // One-to-many relationship
    // AssignedEmployee?: EmployeeDto; // Many-to-one relationship
    // Inventory?: InventoryDto[]; // Generates relationship
}

// StocktakeSchedule Interface
export interface StocktakeScheduleDto {
    GUID: string;
    ID: string; // PK
    Name: string;
    Description: string;
    Frequency: 'Weekly' | 'Monthly' | string;
    IsEnforced: boolean;
    CreatedBy: string;
    CreatedDate: Date;
    UpdatedBy: string;
    UpdatedDate: Date;
    // Relationships
    Employees?: EmployeeDto[]; // Many-to-many relationship
}

// Inventory Interface
export interface InventoryDto {
    // GUID: string;
    ID: string; // PK
    Code: string;
    Description: string;
    Quantity: number;
    Value: number;
    CategoryID: string; // FK
    SubcategoryID: string; // FK
    ThumbnailUrl: string;
    ImageUrl: string;

    StockItemType: any;
    BinLocation: any;

    // Relationships
    // StocktakeItems?: StocktakeItemDto[]; // One-to-many relationship
    // Stocktake?: StocktakeDto; // Generated by relationship
}

// ActionReason Interface
export interface ActionReasonDto {
    GUID: string;
    ID: string; // PK
    Reason: string;
    Description: string;

    // Relationships
    StocktakeItems?: StocktakeItemDto[]; // One-to-many relationship
}


export interface StocktakeItemDto {
    ID: string; // PK
    StocktakeName: string;
    InventoryID: string; // FK to Inventory
    InventoryCode: string;
    InventoryDescription: string;
    InventoryStockItemType: (typeof Enums.StockItemType)[keyof typeof Enums.StockItemType]
    InventoryImageUrl: string;
    InventoryThumbnailUrl: string;
    CostPrice: number | string; // Cost price of the inventory item
    ListPrice: number | string; // UnitPriceExclusive of the inventory item
    StartingQuantity: number;
    CountedQuantity: number | null;
    ExpectedQuantity: number;
    Status: number; // 0 = draft: Default for status mapping
    CountedDate: string | null;
    Notes: string;
    BinLocation: string | null;
    AdjustmentReason: (typeof Enums.StockItemType)[keyof typeof Enums.StockItemType] | null;
    AdjustmentQuantity: number | null;
    AssignedEmployeeID: string; // FK to Employee
    AssignedEmployeeFullName: string;
    IsActive: boolean;
    CreatedBy: string;
    CreatedDate: string; // ISO string format
    ModifiedBy: string;
    ModifiedDate: string; // ISO string format
    RowVersion: string;
    StocktakeItemSource: number;
}

export interface StockTakeFinancialsDto {
    TotalItems: number;
    ItemsCounted: number;
    AdjustedCost: number;
    AdjustedPrice: number;
    CountedCost: number;
    CountedPrice: number;
    ExpectedCost: number;
    ExpectedPrice: number;
}

// Warehouse Interface
export interface WarehouseDto {
    GUID: string;
    ID: string; // PK
    Name: string;
    Description: string;

    // Relationships
    Stocktakes?: StocktakeDto[]; // One-to-many relationship
}

// StocktakeFilter Interface
export interface StocktakeFilterDto {
    GUID: string;
    ID: string; // PK
    StocktakeID: string; // FK to Stocktake
    FilterType: 'Category' | 'Subcategory' | 'Value' | 'Location' | 'All';
    FilterValue: string;

    // Relationships
    Stocktake?: StocktakeDto; // Many-to-one relationship
}

export interface StocktakeTemplateDto {
    ID: string;
    IsActive: boolean;
    CreatedBy: string;
    CreatedDate: string;
    ModifiedBy: string;
    ModifiedDate: string;
    RowVersion: string;
    Name: string;
    Description: string;
    StocktakeTemplateItems?: Partial<StocktakeTemplateItemDto>[];
}

export interface StocktakeTemplateItemDto {
    ID: string;
    IsActive: boolean;
    CreatedBy: string;
    CreatedDate: string;
    ModifiedBy: string;
    ModifiedDate: string;
    RowVersion: string;
    StocktakeTemplateID: string;
    StocktakeTemplateName: string;
    InventoryID: string;
    InventoryDescription: string;
    InventoryCode: string;
    InventoryStockItemType: number;
    PrimaryDisplayImageID: string;
    ImageUrl: string;
    ThumbnailUrl: string;
}
